name: Java on Docker
on: [pull_request]
jobs:
  java_docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Keploy binary
      run: |
        docker build -t keployv2 .

    - name: Checkout samples-java repository
      uses: actions/checkout@v2
      with:
        repository: slayerjain/spring-petclinic-rest
        path: spring-petclinic-rest

    - name: Installing the necessary dependencies
      run: |
        cd spring-petclinic-rest
        ./mvnw dependency:resolve

    - name: Compile the project
      run: |
        cd spring-petclinic-rest
        source ./../.github/workflows/update-java.sh
        ./mvnw compile

    - name: Run the spring-petclinic-rest app
      run: |
        cd spring-petclinic-rest
        source ./../.github/workflows/java-docker.sh